// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-kernel-hmac.sh
// Kernel HMAC placeholder - actual verification uses runtime keys

const hmac = @import("hmac.zig");

// HMAC verification is now performed at runtime using keys from UEFI variables
// This placeholder is kept for compatibility but is not used for actual verification
pub const KERNEL_HMAC = [hmac.HMAC_SIZE]u8{0} ** hmac.HMAC_SIZE;

// Flag to indicate runtime HMAC verification should be used
pub const USE_RUNTIME_HMAC = true;

// The bootloader will:
// 1. Load or generate HMAC key from secure UEFI variables
// 2. Calculate kernel HMAC at runtime
// 3. Store the expected HMAC in UEFI variables on first boot
// 4. Verify kernel integrity on subsequent boots
